### ISSUE TITLE
tag links are broken

### ISSUE THREAD

**Issue by acinader** [parse-community/blog#12]
the tags that aren't a top level like All or Announcement 404 when you click on them.  example: https://blog.parseplatform.org/blog/categories/javascript

**Comment by TomWFox** [comment]
I noticed this too. I'm wondering what behaviour we want here:

1. The tags are shown but don't have links - so at least they won't 404 (for the ones that aren't top level)
2. we remove the tags
3. We add them as new categories but perhaps not top level as there would be too many

Or something else? - I could look at doing a PR for this but think we should work out the desired solution first

**Comment by TomWFox** [comment]
I just did a little test by adding a new category for javascript and that fixes the link without automatically adding the tag to the top level navigation so doing option 3 is relatively easy.

I suppose ideally new categories would be created automatically, but I don't mind creating them manually for the time being so the links aren't broken.

**Comment by TomWFox** [comment]
I've made a branch on my fork which standardises the categories and fixes the broken tags - I can PR this as a quick fix

**Comment by TomWFox** [comment]
Done #14

**Comment by TomWFox** [comment]
Concluded for all historic posts in #17
