### ISSUE TITLE
Community Profile

### ISSUE THREAD

**Issue by TomWFox** [parse-community/blog#19]
The following things need to be written/decided on for the community profile of this repo:

- [x] Code of conduct (#18)

- [x]  License ([43ea819](https://github.com/parse-community/blog/commit/46391527bb5078c308bd69bb2c8161c70dce9f08))

- [ ] ~~Pull request template~~

- [x] Issue template ([cc08f95](
https://github.com/parse-community/blog/commit/cc08f95d3844573a9fbca146c287355a51352586), [7118728](
https://github.com/parse-community/blog/commit/7118728131752edabadc3bc02b20f78dbe4b66a6))

**Comment by acinader** [comment]
any reason we can't use https://github.com/parse-community/parse-server/blob/master/LICENSE for the license?

**Comment by TomWFox** [comment]
Not that I'm aware of, it probably makes sense to have the same license across all the repos.

**Comment by acinader** [comment]
agreed.

**Comment by TomWFox** [comment]
Closing this now as we probably don't need PR templates for this repo.
